# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/run/media/abhishek/linux-a/C++ projects/OOP_Project/BoardGames"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/run/media/abhishek/linux-a/C++ projects/OOP_Project/BoardGames"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/run/media/abhishek/linux-a/C++ projects/OOP_Project/BoardGames/CMakeFiles" "/run/media/abhishek/linux-a/C++ projects/OOP_Project/BoardGames//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/run/media/abhishek/linux-a/C++ projects/OOP_Project/BoardGames/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named BoardGames

# Build rule for target.
BoardGames: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 BoardGames
.PHONY : BoardGames

# fast build rule for target.
BoardGames/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/build
.PHONY : BoardGames/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/main.cpp.s
.PHONY : main.cpp.s

source/buddhichal/buddhichal.o: source/buddhichal/buddhichal.cpp.o
.PHONY : source/buddhichal/buddhichal.o

# target to build an object file
source/buddhichal/buddhichal.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/buddhichal/buddhichal.cpp.o
.PHONY : source/buddhichal/buddhichal.cpp.o

source/buddhichal/buddhichal.i: source/buddhichal/buddhichal.cpp.i
.PHONY : source/buddhichal/buddhichal.i

# target to preprocess a source file
source/buddhichal/buddhichal.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/buddhichal/buddhichal.cpp.i
.PHONY : source/buddhichal/buddhichal.cpp.i

source/buddhichal/buddhichal.s: source/buddhichal/buddhichal.cpp.s
.PHONY : source/buddhichal/buddhichal.s

# target to generate assembly for a file
source/buddhichal/buddhichal.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/buddhichal/buddhichal.cpp.s
.PHONY : source/buddhichal/buddhichal.cpp.s

source/checkers/Engine.o: source/checkers/Engine.cpp.o
.PHONY : source/checkers/Engine.o

# target to build an object file
source/checkers/Engine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/checkers/Engine.cpp.o
.PHONY : source/checkers/Engine.cpp.o

source/checkers/Engine.i: source/checkers/Engine.cpp.i
.PHONY : source/checkers/Engine.i

# target to preprocess a source file
source/checkers/Engine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/checkers/Engine.cpp.i
.PHONY : source/checkers/Engine.cpp.i

source/checkers/Engine.s: source/checkers/Engine.cpp.s
.PHONY : source/checkers/Engine.s

# target to generate assembly for a file
source/checkers/Engine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/checkers/Engine.cpp.s
.PHONY : source/checkers/Engine.cpp.s

source/checkers/MainMenu.o: source/checkers/MainMenu.cpp.o
.PHONY : source/checkers/MainMenu.o

# target to build an object file
source/checkers/MainMenu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/checkers/MainMenu.cpp.o
.PHONY : source/checkers/MainMenu.cpp.o

source/checkers/MainMenu.i: source/checkers/MainMenu.cpp.i
.PHONY : source/checkers/MainMenu.i

# target to preprocess a source file
source/checkers/MainMenu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/checkers/MainMenu.cpp.i
.PHONY : source/checkers/MainMenu.cpp.i

source/checkers/MainMenu.s: source/checkers/MainMenu.cpp.s
.PHONY : source/checkers/MainMenu.s

# target to generate assembly for a file
source/checkers/MainMenu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/checkers/MainMenu.cpp.s
.PHONY : source/checkers/MainMenu.cpp.s

source/checkers/Piece.o: source/checkers/Piece.cpp.o
.PHONY : source/checkers/Piece.o

# target to build an object file
source/checkers/Piece.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/checkers/Piece.cpp.o
.PHONY : source/checkers/Piece.cpp.o

source/checkers/Piece.i: source/checkers/Piece.cpp.i
.PHONY : source/checkers/Piece.i

# target to preprocess a source file
source/checkers/Piece.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/checkers/Piece.cpp.i
.PHONY : source/checkers/Piece.cpp.i

source/checkers/Piece.s: source/checkers/Piece.cpp.s
.PHONY : source/checkers/Piece.s

# target to generate assembly for a file
source/checkers/Piece.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/checkers/Piece.cpp.s
.PHONY : source/checkers/Piece.cpp.s

source/checkers/StateManager.o: source/checkers/StateManager.cpp.o
.PHONY : source/checkers/StateManager.o

# target to build an object file
source/checkers/StateManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/checkers/StateManager.cpp.o
.PHONY : source/checkers/StateManager.cpp.o

source/checkers/StateManager.i: source/checkers/StateManager.cpp.i
.PHONY : source/checkers/StateManager.i

# target to preprocess a source file
source/checkers/StateManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/checkers/StateManager.cpp.i
.PHONY : source/checkers/StateManager.cpp.i

source/checkers/StateManager.s: source/checkers/StateManager.cpp.s
.PHONY : source/checkers/StateManager.s

# target to generate assembly for a file
source/checkers/StateManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/checkers/StateManager.cpp.s
.PHONY : source/checkers/StateManager.cpp.s

source/checkers/checkers.o: source/checkers/checkers.cpp.o
.PHONY : source/checkers/checkers.o

# target to build an object file
source/checkers/checkers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/checkers/checkers.cpp.o
.PHONY : source/checkers/checkers.cpp.o

source/checkers/checkers.i: source/checkers/checkers.cpp.i
.PHONY : source/checkers/checkers.i

# target to preprocess a source file
source/checkers/checkers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/checkers/checkers.cpp.i
.PHONY : source/checkers/checkers.cpp.i

source/checkers/checkers.s: source/checkers/checkers.cpp.s
.PHONY : source/checkers/checkers.s

# target to generate assembly for a file
source/checkers/checkers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/checkers/checkers.cpp.s
.PHONY : source/checkers/checkers.cpp.s

source/checkers/computer.o: source/checkers/computer.cpp.o
.PHONY : source/checkers/computer.o

# target to build an object file
source/checkers/computer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/checkers/computer.cpp.o
.PHONY : source/checkers/computer.cpp.o

source/checkers/computer.i: source/checkers/computer.cpp.i
.PHONY : source/checkers/computer.i

# target to preprocess a source file
source/checkers/computer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/checkers/computer.cpp.i
.PHONY : source/checkers/computer.cpp.i

source/checkers/computer.s: source/checkers/computer.cpp.s
.PHONY : source/checkers/computer.s

# target to generate assembly for a file
source/checkers/computer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/checkers/computer.cpp.s
.PHONY : source/checkers/computer.cpp.s

source/checkers/currClickedPiece.o: source/checkers/currClickedPiece.cpp.o
.PHONY : source/checkers/currClickedPiece.o

# target to build an object file
source/checkers/currClickedPiece.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/checkers/currClickedPiece.cpp.o
.PHONY : source/checkers/currClickedPiece.cpp.o

source/checkers/currClickedPiece.i: source/checkers/currClickedPiece.cpp.i
.PHONY : source/checkers/currClickedPiece.i

# target to preprocess a source file
source/checkers/currClickedPiece.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/checkers/currClickedPiece.cpp.i
.PHONY : source/checkers/currClickedPiece.cpp.i

source/checkers/currClickedPiece.s: source/checkers/currClickedPiece.cpp.s
.PHONY : source/checkers/currClickedPiece.s

# target to generate assembly for a file
source/checkers/currClickedPiece.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/checkers/currClickedPiece.cpp.s
.PHONY : source/checkers/currClickedPiece.cpp.s

source/checkers/gameContext.o: source/checkers/gameContext.cpp.o
.PHONY : source/checkers/gameContext.o

# target to build an object file
source/checkers/gameContext.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/checkers/gameContext.cpp.o
.PHONY : source/checkers/gameContext.cpp.o

source/checkers/gameContext.i: source/checkers/gameContext.cpp.i
.PHONY : source/checkers/gameContext.i

# target to preprocess a source file
source/checkers/gameContext.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/checkers/gameContext.cpp.i
.PHONY : source/checkers/gameContext.cpp.i

source/checkers/gameContext.s: source/checkers/gameContext.cpp.s
.PHONY : source/checkers/gameContext.s

# target to generate assembly for a file
source/checkers/gameContext.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/checkers/gameContext.cpp.s
.PHONY : source/checkers/gameContext.cpp.s

source/checkers/gameover.o: source/checkers/gameover.cpp.o
.PHONY : source/checkers/gameover.o

# target to build an object file
source/checkers/gameover.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/checkers/gameover.cpp.o
.PHONY : source/checkers/gameover.cpp.o

source/checkers/gameover.i: source/checkers/gameover.cpp.i
.PHONY : source/checkers/gameover.i

# target to preprocess a source file
source/checkers/gameover.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/checkers/gameover.cpp.i
.PHONY : source/checkers/gameover.cpp.i

source/checkers/gameover.s: source/checkers/gameover.cpp.s
.PHONY : source/checkers/gameover.s

# target to generate assembly for a file
source/checkers/gameover.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/checkers/gameover.cpp.s
.PHONY : source/checkers/gameover.cpp.s

source/checkers/mandatory.o: source/checkers/mandatory.cpp.o
.PHONY : source/checkers/mandatory.o

# target to build an object file
source/checkers/mandatory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/checkers/mandatory.cpp.o
.PHONY : source/checkers/mandatory.cpp.o

source/checkers/mandatory.i: source/checkers/mandatory.cpp.i
.PHONY : source/checkers/mandatory.i

# target to preprocess a source file
source/checkers/mandatory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/checkers/mandatory.cpp.i
.PHONY : source/checkers/mandatory.cpp.i

source/checkers/mandatory.s: source/checkers/mandatory.cpp.s
.PHONY : source/checkers/mandatory.s

# target to generate assembly for a file
source/checkers/mandatory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/checkers/mandatory.cpp.s
.PHONY : source/checkers/mandatory.cpp.s

source/checkers/multiplayer-offline.o: source/checkers/multiplayer-offline.cpp.o
.PHONY : source/checkers/multiplayer-offline.o

# target to build an object file
source/checkers/multiplayer-offline.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/checkers/multiplayer-offline.cpp.o
.PHONY : source/checkers/multiplayer-offline.cpp.o

source/checkers/multiplayer-offline.i: source/checkers/multiplayer-offline.cpp.i
.PHONY : source/checkers/multiplayer-offline.i

# target to preprocess a source file
source/checkers/multiplayer-offline.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/checkers/multiplayer-offline.cpp.i
.PHONY : source/checkers/multiplayer-offline.cpp.i

source/checkers/multiplayer-offline.s: source/checkers/multiplayer-offline.cpp.s
.PHONY : source/checkers/multiplayer-offline.s

# target to generate assembly for a file
source/checkers/multiplayer-offline.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/checkers/multiplayer-offline.cpp.s
.PHONY : source/checkers/multiplayer-offline.cpp.s

source/chess/boardstate.o: source/chess/boardstate.cpp.o
.PHONY : source/chess/boardstate.o

# target to build an object file
source/chess/boardstate.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/chess/boardstate.cpp.o
.PHONY : source/chess/boardstate.cpp.o

source/chess/boardstate.i: source/chess/boardstate.cpp.i
.PHONY : source/chess/boardstate.i

# target to preprocess a source file
source/chess/boardstate.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/chess/boardstate.cpp.i
.PHONY : source/chess/boardstate.cpp.i

source/chess/boardstate.s: source/chess/boardstate.cpp.s
.PHONY : source/chess/boardstate.s

# target to generate assembly for a file
source/chess/boardstate.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/chess/boardstate.cpp.s
.PHONY : source/chess/boardstate.cpp.s

source/chess/chess.o: source/chess/chess.cpp.o
.PHONY : source/chess/chess.o

# target to build an object file
source/chess/chess.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/chess/chess.cpp.o
.PHONY : source/chess/chess.cpp.o

source/chess/chess.i: source/chess/chess.cpp.i
.PHONY : source/chess/chess.i

# target to preprocess a source file
source/chess/chess.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/chess/chess.cpp.i
.PHONY : source/chess/chess.cpp.i

source/chess/chess.s: source/chess/chess.cpp.s
.PHONY : source/chess/chess.s

# target to generate assembly for a file
source/chess/chess.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/chess/chess.cpp.s
.PHONY : source/chess/chess.cpp.s

source/chess/declare.o: source/chess/declare.cpp.o
.PHONY : source/chess/declare.o

# target to build an object file
source/chess/declare.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/chess/declare.cpp.o
.PHONY : source/chess/declare.cpp.o

source/chess/declare.i: source/chess/declare.cpp.i
.PHONY : source/chess/declare.i

# target to preprocess a source file
source/chess/declare.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/chess/declare.cpp.i
.PHONY : source/chess/declare.cpp.i

source/chess/declare.s: source/chess/declare.cpp.s
.PHONY : source/chess/declare.s

# target to generate assembly for a file
source/chess/declare.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/chess/declare.cpp.s
.PHONY : source/chess/declare.cpp.s

source/chess/depthguess.o: source/chess/depthguess.cpp.o
.PHONY : source/chess/depthguess.o

# target to build an object file
source/chess/depthguess.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/chess/depthguess.cpp.o
.PHONY : source/chess/depthguess.cpp.o

source/chess/depthguess.i: source/chess/depthguess.cpp.i
.PHONY : source/chess/depthguess.i

# target to preprocess a source file
source/chess/depthguess.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/chess/depthguess.cpp.i
.PHONY : source/chess/depthguess.cpp.i

source/chess/depthguess.s: source/chess/depthguess.cpp.s
.PHONY : source/chess/depthguess.s

# target to generate assembly for a file
source/chess/depthguess.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/chess/depthguess.cpp.s
.PHONY : source/chess/depthguess.cpp.s

source/chess/diff.o: source/chess/diff.cpp.o
.PHONY : source/chess/diff.o

# target to build an object file
source/chess/diff.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/chess/diff.cpp.o
.PHONY : source/chess/diff.cpp.o

source/chess/diff.i: source/chess/diff.cpp.i
.PHONY : source/chess/diff.i

# target to preprocess a source file
source/chess/diff.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/chess/diff.cpp.i
.PHONY : source/chess/diff.cpp.i

source/chess/diff.s: source/chess/diff.cpp.s
.PHONY : source/chess/diff.s

# target to generate assembly for a file
source/chess/diff.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/chess/diff.cpp.s
.PHONY : source/chess/diff.cpp.s

source/chess/display.o: source/chess/display.cpp.o
.PHONY : source/chess/display.o

# target to build an object file
source/chess/display.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/chess/display.cpp.o
.PHONY : source/chess/display.cpp.o

source/chess/display.i: source/chess/display.cpp.i
.PHONY : source/chess/display.i

# target to preprocess a source file
source/chess/display.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/chess/display.cpp.i
.PHONY : source/chess/display.cpp.i

source/chess/display.s: source/chess/display.cpp.s
.PHONY : source/chess/display.s

# target to generate assembly for a file
source/chess/display.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/chess/display.cpp.s
.PHONY : source/chess/display.cpp.s

source/chess/eval.o: source/chess/eval.cpp.o
.PHONY : source/chess/eval.o

# target to build an object file
source/chess/eval.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/chess/eval.cpp.o
.PHONY : source/chess/eval.cpp.o

source/chess/eval.i: source/chess/eval.cpp.i
.PHONY : source/chess/eval.i

# target to preprocess a source file
source/chess/eval.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/chess/eval.cpp.i
.PHONY : source/chess/eval.cpp.i

source/chess/eval.s: source/chess/eval.cpp.s
.PHONY : source/chess/eval.s

# target to generate assembly for a file
source/chess/eval.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/chess/eval.cpp.s
.PHONY : source/chess/eval.cpp.s

source/chess/getarray.o: source/chess/getarray.cpp.o
.PHONY : source/chess/getarray.o

# target to build an object file
source/chess/getarray.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/chess/getarray.cpp.o
.PHONY : source/chess/getarray.cpp.o

source/chess/getarray.i: source/chess/getarray.cpp.i
.PHONY : source/chess/getarray.i

# target to preprocess a source file
source/chess/getarray.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/chess/getarray.cpp.i
.PHONY : source/chess/getarray.cpp.i

source/chess/getarray.s: source/chess/getarray.cpp.s
.PHONY : source/chess/getarray.s

# target to generate assembly for a file
source/chess/getarray.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/chess/getarray.cpp.s
.PHONY : source/chess/getarray.cpp.s

source/chess/isattacked.o: source/chess/isattacked.cpp.o
.PHONY : source/chess/isattacked.o

# target to build an object file
source/chess/isattacked.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/chess/isattacked.cpp.o
.PHONY : source/chess/isattacked.cpp.o

source/chess/isattacked.i: source/chess/isattacked.cpp.i
.PHONY : source/chess/isattacked.i

# target to preprocess a source file
source/chess/isattacked.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/chess/isattacked.cpp.i
.PHONY : source/chess/isattacked.cpp.i

source/chess/isattacked.s: source/chess/isattacked.cpp.s
.PHONY : source/chess/isattacked.s

# target to generate assembly for a file
source/chess/isattacked.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/chess/isattacked.cpp.s
.PHONY : source/chess/isattacked.cpp.s

source/chess/ischeck.o: source/chess/ischeck.cpp.o
.PHONY : source/chess/ischeck.o

# target to build an object file
source/chess/ischeck.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/chess/ischeck.cpp.o
.PHONY : source/chess/ischeck.cpp.o

source/chess/ischeck.i: source/chess/ischeck.cpp.i
.PHONY : source/chess/ischeck.i

# target to preprocess a source file
source/chess/ischeck.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/chess/ischeck.cpp.i
.PHONY : source/chess/ischeck.cpp.i

source/chess/ischeck.s: source/chess/ischeck.cpp.s
.PHONY : source/chess/ischeck.s

# target to generate assembly for a file
source/chess/ischeck.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/chess/ischeck.cpp.s
.PHONY : source/chess/ischeck.cpp.s

source/chess/ischeckedaftermove.o: source/chess/ischeckedaftermove.cpp.o
.PHONY : source/chess/ischeckedaftermove.o

# target to build an object file
source/chess/ischeckedaftermove.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/chess/ischeckedaftermove.cpp.o
.PHONY : source/chess/ischeckedaftermove.cpp.o

source/chess/ischeckedaftermove.i: source/chess/ischeckedaftermove.cpp.i
.PHONY : source/chess/ischeckedaftermove.i

# target to preprocess a source file
source/chess/ischeckedaftermove.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/chess/ischeckedaftermove.cpp.i
.PHONY : source/chess/ischeckedaftermove.cpp.i

source/chess/ischeckedaftermove.s: source/chess/ischeckedaftermove.cpp.s
.PHONY : source/chess/ischeckedaftermove.s

# target to generate assembly for a file
source/chess/ischeckedaftermove.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/chess/ischeckedaftermove.cpp.s
.PHONY : source/chess/ischeckedaftermove.cpp.s

source/chess/makemove.o: source/chess/makemove.cpp.o
.PHONY : source/chess/makemove.o

# target to build an object file
source/chess/makemove.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/chess/makemove.cpp.o
.PHONY : source/chess/makemove.cpp.o

source/chess/makemove.i: source/chess/makemove.cpp.i
.PHONY : source/chess/makemove.i

# target to preprocess a source file
source/chess/makemove.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/chess/makemove.cpp.i
.PHONY : source/chess/makemove.cpp.i

source/chess/makemove.s: source/chess/makemove.cpp.s
.PHONY : source/chess/makemove.s

# target to generate assembly for a file
source/chess/makemove.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/chess/makemove.cpp.s
.PHONY : source/chess/makemove.cpp.s

source/chess/minimaxinit.o: source/chess/minimaxinit.cpp.o
.PHONY : source/chess/minimaxinit.o

# target to build an object file
source/chess/minimaxinit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/chess/minimaxinit.cpp.o
.PHONY : source/chess/minimaxinit.cpp.o

source/chess/minimaxinit.i: source/chess/minimaxinit.cpp.i
.PHONY : source/chess/minimaxinit.i

# target to preprocess a source file
source/chess/minimaxinit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/chess/minimaxinit.cpp.i
.PHONY : source/chess/minimaxinit.cpp.i

source/chess/minimaxinit.s: source/chess/minimaxinit.cpp.s
.PHONY : source/chess/minimaxinit.s

# target to generate assembly for a file
source/chess/minimaxinit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/chess/minimaxinit.cpp.s
.PHONY : source/chess/minimaxinit.cpp.s

source/chess/minmax.o: source/chess/minmax.cpp.o
.PHONY : source/chess/minmax.o

# target to build an object file
source/chess/minmax.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/chess/minmax.cpp.o
.PHONY : source/chess/minmax.cpp.o

source/chess/minmax.i: source/chess/minmax.cpp.i
.PHONY : source/chess/minmax.i

# target to preprocess a source file
source/chess/minmax.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/chess/minmax.cpp.i
.PHONY : source/chess/minmax.cpp.i

source/chess/minmax.s: source/chess/minmax.cpp.s
.PHONY : source/chess/minmax.s

# target to generate assembly for a file
source/chess/minmax.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/chess/minmax.cpp.s
.PHONY : source/chess/minmax.cpp.s

source/chess/move.o: source/chess/move.cpp.o
.PHONY : source/chess/move.o

# target to build an object file
source/chess/move.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/chess/move.cpp.o
.PHONY : source/chess/move.cpp.o

source/chess/move.i: source/chess/move.cpp.i
.PHONY : source/chess/move.i

# target to preprocess a source file
source/chess/move.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/chess/move.cpp.i
.PHONY : source/chess/move.cpp.i

source/chess/move.s: source/chess/move.cpp.s
.PHONY : source/chess/move.s

# target to generate assembly for a file
source/chess/move.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/chess/move.cpp.s
.PHONY : source/chess/move.cpp.s

source/chess/translatefen.o: source/chess/translatefen.cpp.o
.PHONY : source/chess/translatefen.o

# target to build an object file
source/chess/translatefen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/chess/translatefen.cpp.o
.PHONY : source/chess/translatefen.cpp.o

source/chess/translatefen.i: source/chess/translatefen.cpp.i
.PHONY : source/chess/translatefen.i

# target to preprocess a source file
source/chess/translatefen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/chess/translatefen.cpp.i
.PHONY : source/chess/translatefen.cpp.i

source/chess/translatefen.s: source/chess/translatefen.cpp.s
.PHONY : source/chess/translatefen.s

# target to generate assembly for a file
source/chess/translatefen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoardGames.dir/build.make CMakeFiles/BoardGames.dir/source/chess/translatefen.cpp.s
.PHONY : source/chess/translatefen.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... BoardGames"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... source/buddhichal/buddhichal.o"
	@echo "... source/buddhichal/buddhichal.i"
	@echo "... source/buddhichal/buddhichal.s"
	@echo "... source/checkers/Engine.o"
	@echo "... source/checkers/Engine.i"
	@echo "... source/checkers/Engine.s"
	@echo "... source/checkers/MainMenu.o"
	@echo "... source/checkers/MainMenu.i"
	@echo "... source/checkers/MainMenu.s"
	@echo "... source/checkers/Piece.o"
	@echo "... source/checkers/Piece.i"
	@echo "... source/checkers/Piece.s"
	@echo "... source/checkers/StateManager.o"
	@echo "... source/checkers/StateManager.i"
	@echo "... source/checkers/StateManager.s"
	@echo "... source/checkers/checkers.o"
	@echo "... source/checkers/checkers.i"
	@echo "... source/checkers/checkers.s"
	@echo "... source/checkers/computer.o"
	@echo "... source/checkers/computer.i"
	@echo "... source/checkers/computer.s"
	@echo "... source/checkers/currClickedPiece.o"
	@echo "... source/checkers/currClickedPiece.i"
	@echo "... source/checkers/currClickedPiece.s"
	@echo "... source/checkers/gameContext.o"
	@echo "... source/checkers/gameContext.i"
	@echo "... source/checkers/gameContext.s"
	@echo "... source/checkers/gameover.o"
	@echo "... source/checkers/gameover.i"
	@echo "... source/checkers/gameover.s"
	@echo "... source/checkers/mandatory.o"
	@echo "... source/checkers/mandatory.i"
	@echo "... source/checkers/mandatory.s"
	@echo "... source/checkers/multiplayer-offline.o"
	@echo "... source/checkers/multiplayer-offline.i"
	@echo "... source/checkers/multiplayer-offline.s"
	@echo "... source/chess/boardstate.o"
	@echo "... source/chess/boardstate.i"
	@echo "... source/chess/boardstate.s"
	@echo "... source/chess/chess.o"
	@echo "... source/chess/chess.i"
	@echo "... source/chess/chess.s"
	@echo "... source/chess/declare.o"
	@echo "... source/chess/declare.i"
	@echo "... source/chess/declare.s"
	@echo "... source/chess/depthguess.o"
	@echo "... source/chess/depthguess.i"
	@echo "... source/chess/depthguess.s"
	@echo "... source/chess/diff.o"
	@echo "... source/chess/diff.i"
	@echo "... source/chess/diff.s"
	@echo "... source/chess/display.o"
	@echo "... source/chess/display.i"
	@echo "... source/chess/display.s"
	@echo "... source/chess/eval.o"
	@echo "... source/chess/eval.i"
	@echo "... source/chess/eval.s"
	@echo "... source/chess/getarray.o"
	@echo "... source/chess/getarray.i"
	@echo "... source/chess/getarray.s"
	@echo "... source/chess/isattacked.o"
	@echo "... source/chess/isattacked.i"
	@echo "... source/chess/isattacked.s"
	@echo "... source/chess/ischeck.o"
	@echo "... source/chess/ischeck.i"
	@echo "... source/chess/ischeck.s"
	@echo "... source/chess/ischeckedaftermove.o"
	@echo "... source/chess/ischeckedaftermove.i"
	@echo "... source/chess/ischeckedaftermove.s"
	@echo "... source/chess/makemove.o"
	@echo "... source/chess/makemove.i"
	@echo "... source/chess/makemove.s"
	@echo "... source/chess/minimaxinit.o"
	@echo "... source/chess/minimaxinit.i"
	@echo "... source/chess/minimaxinit.s"
	@echo "... source/chess/minmax.o"
	@echo "... source/chess/minmax.i"
	@echo "... source/chess/minmax.s"
	@echo "... source/chess/move.o"
	@echo "... source/chess/move.i"
	@echo "... source/chess/move.s"
	@echo "... source/chess/translatefen.o"
	@echo "... source/chess/translatefen.i"
	@echo "... source/chess/translatefen.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

